/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.CreditCard;

import BE.CreditCard;
import GUI.WindowCtrl;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author notandi
 */
public class AddCreditCardInfoJFrame extends WindowCtrl
{

    private CreditCard creditCard = null;
    private AddCreditCardInfoJFrame addCredit;

    /**
     * Creates new form AddCreditCardInfoJFrame
     */
    public AddCreditCardInfoJFrame()
    {
        initComponents();
        WindowCtrl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnAddCreditInfo = new javax.swing.JButton();
        pnlCreditnr = new javax.swing.JPanel();
        txtCreditnr = new javax.swing.JTextField();
        pnlCVC = new javax.swing.JPanel();
        txtCVC = new javax.swing.JTextField();
        pnlExp = new javax.swing.JPanel();
        txtExp = new javax.swing.JTextField();
        txtExpY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New Credit Card information"));

        btnAddCreditInfo.setText("Add Credit Card");
        btnAddCreditInfo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddCreditInfoActionPerformed(evt);
            }
        });

        pnlCreditnr.setBorder(javax.swing.BorderFactory.createTitledBorder("Card Number:"));

        txtCreditnr.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtCreditnrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreditnrLayout = new javax.swing.GroupLayout(pnlCreditnr);
        pnlCreditnr.setLayout(pnlCreditnrLayout);
        pnlCreditnrLayout.setHorizontalGroup(
            pnlCreditnrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCreditnr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlCreditnrLayout.setVerticalGroup(
            pnlCreditnrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCreditnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlCVC.setBorder(javax.swing.BorderFactory.createTitledBorder("CVC"));

        javax.swing.GroupLayout pnlCVCLayout = new javax.swing.GroupLayout(pnlCVC);
        pnlCVC.setLayout(pnlCVCLayout);
        pnlCVCLayout.setHorizontalGroup(
            pnlCVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCVC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlCVCLayout.setVerticalGroup(
            pnlCVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlExp.setBorder(javax.swing.BorderFactory.createTitledBorder("Expiration (MM/YY)"));

        jLabel1.setText("/");

        javax.swing.GroupLayout pnlExpLayout = new javax.swing.GroupLayout(pnlExp);
        pnlExp.setLayout(pnlExpLayout);
        pnlExpLayout.setHorizontalGroup(
            pnlExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExpLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(txtExp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExpY, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlExpLayout.setVerticalGroup(
            pnlExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtExpY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCreditnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAddCreditInfo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(pnlExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pnlCreditnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCreditInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCreditnrActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtCreditnrActionPerformed
    {//GEN-HEADEREND:event_txtCreditnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditnrActionPerformed

    private void btnAddCreditInfoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddCreditInfoActionPerformed
    {//GEN-HEADEREND:event_btnAddCreditInfoActionPerformed
        try
        {
            int creditNr = new Scanner(txtCreditnr.getText().trim()).nextInt();

            int exp = new Scanner(txtExp.getText().trim()).nextInt();

//        int expY = new Scanner(txtExpY.getText().trim()).nextInt();
//        if (expY == 0)
//        {
//            throw new RuntimeException("Expiration date is required.");
//        }
            int cvc = new Scanner(txtCVC.getText().trim()).nextInt();

            creditCard = new CreditCard(creditNr, exp, cvc);

            creditCard = addCredit.getCreditCard();
            if (creditCard != null)
            {
                try
                {
                    // add the credit card to the model and also update the table model.
                    creditMgr.addCreditCard(creditCard);
                    creditModel.setCreditCardList(creditMgr.getAll());
                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(this, "Unable to add Credit Card", "Add Credit Card", JOptionPane.ERROR_MESSAGE);
                }                
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddCreditInfoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    public CreditCard getCreditCard()
    {
        return creditCard;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCreditInfo;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlCVC;
    private javax.swing.JPanel pnlCreditnr;
    private javax.swing.JPanel pnlExp;
    private javax.swing.JTextField txtCVC;
    private javax.swing.JTextField txtCreditnr;
    private javax.swing.JTextField txtExp;
    private javax.swing.JTextField txtExpY;
    // End of variables declaration//GEN-END:variables
}
